version: '3.9'
services:
  pg_auction_server:
    image: postgres:16.2-alpine3.19
    container_name: pg_auction_server
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=auction_server
    ports:
      - 9001:5432
    volumes:
      - pg_auction_server_data:/var/lib/postgresql/data
volumes:
  pg_auction_server_data:
    driver: local