version: '3.9'
services:
  pg_auction_server:
    image: postgres:16.2-alpine3.19
    container_name: pg_auction_server
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=auction_server
    ports:
      - 9001:5432
    volumes:
      - pg_auction_server_data:/var/lib/postgresql/data

  mongo_search_server:
    container_name: mongo_serach_server
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root   
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 9002:27017
    volumes:
      - mongo_serach_server_data:/data/db
  rabbitmq_server:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_server
    ports:
      - 5673:5672
      - 15672:15672
volumes:
  pg_auction_server_data:
    driver: local
  mongo_serach_server_data:
    driver: local