version: "3.9"
services:
  pg_auction_server:
    image: postgres:16.2-alpine3.19
    container_name: pg_auction_server
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=auction_server
    ports:
      - 9001:5432
    volumes:
      - pg_auction_server_data:/var/lib/postgresql/data

  mongo_search_server:
    container_name: mongo_serach_server
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 9002:27017
    volumes:
      - mongo_serach_server_data:/data/db

  rabbitmq_server:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_server
    ports:
      - 5673:5672
      - 15672:15672

  auction_svc_server:
    image: pzwitthawasdev/auctionservice:latest
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMQ__Host=rabbitmq_server
      - RabbitMQ__Port=5672
      - ConnectionStrings__DefaultConnection=Server=pg_auction_server;Port=5432;Database=auction_server;User Id=admin;Password=admin123
      - IdentityServiceUrl=http://identity_svc_server
    ports:
      - 7001:80
    depends_on:
      - pg_auction_server
      - rabbitmq_server

  serach_svc_server:
    image: pzwitthawasdev/searchservice:latest
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMQ__Host=rabbitmq_server
      - RabbitMQ__Port=5672
      - ConnectionStrings__DefaultConnection=mongodb://root:mongopw@mongo_search_server:27017
      - AuctionServiceUrl=http://auction_svc_server
    ports:
      - 7002:80
    depends_on:
      - mongo_search_server
      - rabbitmq_server

  identity_svc_server:
    image: pzwitthawasdev/identityserver:latest
    build:
      context: .
      dockerfile: src/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=pg_auction_server;Port=5432;Database=identity_server;User Id=admin;Password=admin123
    ports:
      - 5001:80
    depends_on:
      - pg_auction_server

  gateway_svc_server:
    image: pzwitthawasdev/gatwaysever:latest
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 6001:80

volumes:
  pg_auction_server_data:
    driver: local
  mongo_serach_server_data:
    driver: local
